### ISSUE TITLE
Add support for widescreen

### ISSUE THREAD

**Issue by Sylk** [zero334/Dawn-of-War-Widescreen-Fix#1]
I've got a monitor that runs 2560x1080 and would like for your patcher to support that as well.

**Comment by Sylk** [comment]
The value you're going to want to add for that resolution is 26B41740, however you still get bars.

**Comment by zero334** [comment]
I can add this value without a problem, but I'm not able to test this, because I am lacking a screen with this resolution.
I think the aspect ratios can also be calculated, but there might be some distorsion.
Shall I still add this?

**Comment by Sylk** [comment]
@zero334 I'll test it. Go ahead and add it as a PR if you'd like.

**Comment by zero334** [comment]
@Sylk I implemented a potential fix. See the PR #2

**Comment by Sylk** [comment]
Looked great, go ahead and merge it on in.

**Comment by zero334** [comment]
Alright, thank you very much for testing!
The changes are now in master. I will create a new build asap.
