### ISSUE TITLE
NullReferenceException 

### ISSUE THREAD

**Issue by vrubayka** [zero334/Dawn-of-War-Widescreen-Fix#3]
When I try to patch the .exe, I get the following error: 

System.NullReferenceException: Object reference not set to an instance of an object.
   in Dawn_of_War_Widescreen_Fix.AttributeStorage.CheckAspectRatioValues()
   in Dawn_of_War_Widescreen_Fix.Form.BtnStart_Click(Object sender, EventArgs e)
   in System.Windows.Forms.Control.OnClick(EventArgs e)
   in System.Windows.Forms.Button.OnClick(EventArgs e)
   in System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   in System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   in System.Windows.Forms.Control.WndProc(Message& m)
   in System.Windows.Forms.ButtonBase.WndProc(Message& m)
   in System.Windows.Forms.Button.WndProc(Message& m)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

1.51 Retail version, Windows 10 x64 Build 19042.928, .NET Framework 4 installed.

**Comment by vrubayka** [comment]
Perhaps you could patch the .exe for me? 

https://drive.google.com/drive/folders/1rFJs7CBBVcqR7gfYKjbsdIY6BHlNP_Ak?usp=sharing

For 1366x768 (that's categorized as 16:10, perhaps 1360x768 works better)

**Comment by zero334** [comment]
Hi @vrubayka 
I will build a new version of the tool which should work later.

**Comment by zero334** [comment]
@vrubayka I just released [version 1.1](https://github.com/zero334/Dawn-of-War-Widescreen-Fix/releases/tag/1.1)
Please try it with the new version and tell me if you still get an error.

**Comment by vrubayka** [comment]
Works great on 1366x768 (auto detect), thanks!

**Comment by zero334** [comment]
You're welcome! Thanks for testing.
