### ISSUE TITLE
Doesn't work with Anniversary Edition on Steam?

### ISSUE THREAD

**Issue by Undertow6248** [zero334/Dawn-of-War-Widescreen-Fix#5]
Recently redownloaded DoW 1 from Steam, which is now anniversary edition. I applied this fix by dragging and dropping, but it didn't make any difference to the resolution. It was still in 4:3.

**Comment by Undertow6248** [comment]
Correction: the auto-detect option didn't work but selecting 1920x1080 did. Leaving open since may still be a bug re auto detect

**Comment by zero334** [comment]
@Spottyfriend If you like, we could have a look why `Screen.PrimaryScreen.Bounds` did not return 1920x1080 for you. Do you have multiple screens with different resolutions?

**Comment by Undertow6248** [comment]
I don't mind since it's not a bug that's a problem for me now, but yeah I do actually have 2 monitors and one is 4:3 so maybe that was the issue
